---
elasticsearch: 
    feeder: 
        srcdir: ../../metadata
        tempdirnameprefix: eumetsat-pn-json-results_
        endpoint:
            cluster.name: eumetsat-cluster
            host: localhost
            port: 9300
            index: eumetsat-catalogue
            type: product
        # set this to false to not send documents to index
        index: true
        #limit: 10
...