---
elasticsearch:
    app:
        port: 4567
        searchendpoint:
            url: http://localhost:9200/
            # these are used for Java client:
            host: localhost
            port: 9200
            index: eumetsat-catalogue
            type: product
            paths:
                search: _search
                productinfo: eumetsat-catalogue/product/
        name: Elasticsearch
        # must match webapp name in servlet container:
        path: elasticsearch