---
elasticsearch:
    app:
        port: 4567
        searchendpoint:
            url: http://localhost:9200/
            paths:
                search: _search
                productinfo: eumetsat-catalogue/product/
        autocomplete: http://eumetsat-catalogue/product/_search
        name: Elasticsearch
        # must match webapp name in servlet container:
        path: elasticsearch