---
elasticsearch:
    app:
        port: 4567
        searchendpoint:
            url: http://localhost:9200/
            # these are used for Java client:
            host: localhost
            # 9200 = HTTP, 9300 = node to node / Java client
            port: 9300
            index: eumetsat-catalogue
            type: product
            cluster: eumetsat-cluster
            paths:
                search: _search
                productinfo: eumetsat-catalogue/product/
        name: Elasticsearch
        # must match webapp name in servlet container:
        path: elasticsearch